cargo-features = ["edition2024"]

[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
fnv = "1.0.7"
itertools = "0.13.0"
memoize = "0.4.2"
nom = "7.1.3"
petgraph = "0.6.5"
