cargo-features = ["edition2024"]

[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.93"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
fnv = "1.0.7"
nom = "7.1.3"
petgraph = "0.6.5"
